### ISSUE TITLE
How to build for android

### ISSUE THREAD

**Issue by duaraghav8** [nicopace/ionic-elastichat#1]
I'm kind of new to Ionic.

So I was successfully able to `ionic serve` the app onto the browser and it looks awesome.

But how do I produce the `.apk` for this?

When I tried
`ionic platform add android`
then 
`ionic build android`,

the apk is produced. But upon installing this apk and opening it up, the screen is blank (white) except for a small left-pointing arrow in the top left of the app.

Does your structure differ from the traditional one in a way that it could hinder the proper build? Or are there any other tasks to be performed before deployment?

**Comment by nicopace** [comment]
No... it should work straight away. Let me know what you find!
